import { Header } from "@/components/main/header/Header";
import { Logo } from "@/components/main/logo/Logo";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col overflow-hidden">
        <div className="flex h-screen flex-col overflow-hidden">
          <Header>
            <Logo />
          </Header>
          <main className="flex min-h-0 flex-1 overflow-hidden">{children}</main>
        </div>
      </body>
    </html>
  );
}
